{{ if .Site.Params.DecapCMS.development }}
# Development mode configuration
backend:
  name: test-repo
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts:
    - "127.0.0.1"
{{ else }}
# Production mode configuration
backend:
  name: git-gateway
  branch: "{{ .Site.Params.DecapCMS.branch }}"
{{ end }}
# Folder for storing media files
media_folder: "{{ .Site.Params.DecapCMS.media }}"
# Public URL path for accessing media files
public_folder: "{{ .Site.Params.DecapCMS.public }}"
# Publish mode for content (e.g., editorial workflow)
publish_mode: {{ .Site.Params.DecapCMS.PublishMode }}
# URL of the deployed site
site_url: "{{ .Site.BaseURL }}"
# Display URL for the site
display_url: "{{ .Site.BaseURL }}"
{{ if isset .Site.Params.DecapCMS "logo" }}
# Custom Site Logo URL
logo_url: "{{ .Site.Params.DecapCMS.logo }}"
{{ end }}
# Show preview links in the CMS
show_preview_links: {{ .Site.Params.DecapCMS.preview }}
# Disable search for faster rendering
search: {{ .Site.Params.DecapCMS.search }}

collections:
{{ if .Site.Params.DecapSettings }}
  - label: "Decap Config"
    name: "Decap Config"
    editor:
      preview: false
    files:
      - label: "Parameters"
        name: "params"
        file: "config/_default/params.toml"
        fields:
          - label: Decap CMS
            name: DecapCMS
            widget: object
            fields:
              - { label: "Development", name: "development", widget: "boolean", required: true , default: false}
              - { label: "Branch", name: "branch", widget: "string", required: false , default: "main"}
              - { label: "Media Folder", name: "media", widget: "string", required: true , default: "/static/images"}
              - { label: "Public Folder", name: "public", widget: "string", required: true , default: "/images"}
              - { label: "Publish Mode", name: "PublishMode", widget: "select", options: ["editorial_workflow", "default"], required: true, default: "default" }
              - { label: "Custom Logo", name: "logo", widget: "string", required: false}
              - { label: "Show Preview links", name: "preview", widget: "boolean", required: true , default: true}
              - { label: "Enable Search", name: "search", widget: "boolean", required: true , default: true}
{{ end }}