{{ if .Site.Params.DecapCMS.development }}
# Development mode configuration
backend:
  name: test-repo
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts:
    - "127.0.0.1"
{{ else }}
# Production mode configuration
backend:
  name: git-gateway
  branch: "{{ .Site.Params.DecapCMS.branch }}"
{{ end }}
# Folder for storing media files
media_folder: "{{ .Site.Params.DecapCMS.media }}"
# Public URL path for accessing media files
public_folder: "{{ .Site.Params.DecapCMS.public }}"
# Publish mode for content (e.g., editorial workflow)
publish_mode: {{ .Site.Params.DecapCMS.PublishMode }}
# URL of the deployed site
site_url: "{{ .Site.BaseURL }}"
# Display URL for the site
display_url: "{{ .Site.BaseURL }}"
{{ if isset .Site.Params.DecapCMS "logo" }}
# Custom Site Logo URL
logo_url: "{{ .Site.Params.DecapCMS.logo }}"
{{ end }}
# Show preview links in the CMS
show_preview_links: {{ .Site.Params.DecapCMS.preview }}
# Disable search for faster rendering
search: {{ .Site.Params.DecapCMS.search }}

collections:
  # All Posts
  - label: "Posts"
    name: "posts"
    editor:
      preview: true
    folder: "content/posts"
    create: true
    nested:
      depth: 100
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Show Summary", name: "showSummary", widget: "boolean", default: false, required: true }
      - { label: "Show Table of Contents", name: "showTableOfContents", widget: "boolean", default: true, required: true }
      - { label: "Show Word Count", name: "showWordCount", widget: "boolean", default: true, required: false }
      - { label: "Show Comments", name: "showComments", widget: "boolean", default: false, required: false }
      - { label: "Newsletter", name: "newsletter", widget: "boolean", default: true, required: false }
      - { label: "Show Date", name: "showDate", widget: "boolean", default: true, required: true }
      - { label: "Show Date Updated", name: "showDateUpdated", widget: "boolean", default: false, required: false }
      - { label: "Show Heading Anchors", name: "showHeadingAnchors", widget: "boolean", default: true, required: true }
      - { label: "Show Pagination", name: "showPagination", widget: "boolean", default: true, required: true }
      - { label: "Show Reading Time", name: "showReadingTime", widget: "boolean", default: true, required: true }
      - { label: "Show Taxonomies", name: "showTaxonomies", widget: "boolean", default: true, required: true }
      - { label: "Sharing Links", name: "sharingLinks", widget: "boolean", default: true, required: true }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, required: true, options: [{{ partial "tags-options.html" . }}] }
      - { label: "Categories", name: "categories", widget: "select", multiple: true, required: true, options: [{{ partial "categories-options.html" . }}] }
      - { label: "Series", name: "series", widget: "select", multiple: true, required: true, options: [{{ partial "series-options.html" . }}] }
      - { label: "Series Order", name: "series_order", widget: "select", required: false, options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50"] }
      - { label: "Author", name: "author", widget: "select", required: true , options: [{{ partial "authors-options.html" . }}], default: "{{ .Site.Author.name }}" }
      - { label: "Draft",name: "draft", widget: "boolean",default: false, required: true }
      - { label: "Body", name: "body", widget: "markdown" }
    meta: { path: { widget: string, label: "Path", index_file: "index" } }




# Decap Cms Settings 
{{ if .Site.Params.DecapSettings }}
  - label: "Decap Config"
    name: "Decap Config"
    editor:
      preview: false
    files:
      - label: "Parameters"
        name: "params"
        file: "config/_default/params.toml"
        fields:
          - label: Decap CMS
            name: DecapCMS
            widget: object
            fields:
              - { label: "Development", name: "development", widget: "boolean", required: true , default: false}
              - { label: "Branch", name: "branch", widget: "string", required: false , default: "main"}
              - { label: "Media Folder", name: "media", widget: "string", required: true , default: "/static/images"}
              - { label: "Public Folder", name: "public", widget: "string", required: true , default: "/images"}
              - { label: "Publish Mode", name: "PublishMode", widget: "select", options: ["editorial_workflow", "default"], required: true, default: "default" }
              - { label: "Custom Logo", name: "logo", widget: "string", required: false}
              - { label: "Show Preview links", name: "preview", widget: "boolean", required: true , default: true}
              - { label: "Enable Search", name: "search", widget: "boolean", required: true , default: true}
{{ end }}

# Blowfish Theme Settings
{{ if .Site.Params.BlowfishSettings }}
  # Config Files
  - name: "Site Configuration"
    label: "Site Configuration"
    editor:
      preview: false
    files:
      # config/_default/config.toml
      - file: "config/_default/config.toml"
        label: "Hugo Config"
        name: "Hugo Config"
        fields:
          - { label: "Base URL", name: "baseURL", widget: "string", pattern: [ '^(https?|http):\/\/[^\s/$.?#].[^\s]*$', "Must be a valid URL" ], required: true, default: "{{ .Site.BaseURL }}" }
          - { label: "Theme Name", name: "theme", widget: "string", required: true, default: "blowfish" }
          - { label: "Pluralize List Titles", name: "pluralizeListTitles", widget: "boolean", required: false, default: true }
          - {
              label: "Default Content Language", name: "defaultContentLanguage", widget: "select", required: true,
              options: [
                  { label: "English", value: "en" },
                  { label: "Arabic", value: "ar" },
                  { label: "Bulgarian", value: "bg" },
                  { label: "Bengali", value: "bn" },
                  { label: "Catalan", value: "ca" },
                  { label: "German", value: "de" },
                  { label: "Spanish", value: "es" },
                  { label: "Finnish", value: "fi" },
                  { label: "French", value: "fr" },
                  { label: "Hebrew", value: "he" },
                  { label: "Croatian", value: "hr" },
                  { label: "Hungarian", value: "hu" },
                  { label: "Indonesian", value: "id" },
                  { label: "Italian", value: "it" },
                  { label: "Japanese", value: "ja" },
                  { label: "Korean", value: "ko" },
                  { label: "Polish", value: "pl" },
                  { label: "Portuguese (Brazil)", value: "pt-BR" },
                  { label: "Portuguese (Portugal)", value: "pt-PT" },
                  { label: "Romanian", value: "ro" },
                  { label: "Russian", value: "ru" },
                  { label: "Turkish", value: "tr" },
                  { label: "Vietnamese", value: "vi" },
                  { label: "Chinese (Simplified)", value: "zh-CN" },
                  { label: "Chinese (Traditional)", value: "zh-TW" }
                  ]
            }
          - { label: "Paginate", name: "paginate", widget: "number", required: true, default: 10, value_type: "int", min: 10, max: 50 }
          - { label: "Summary Length", name: "summaryLength", widget: "number", required: true, default: 0, value_type: "int", min: 0, max: 50 }
          - { label: "Enable Robots TXT", name: "enableRobotsTXT", widget: "boolean", default: true }
          - { label: "Build Drafts", name: "buildDrafts", widget: "boolean", required: false, default: false }
          - { label: "Build Expired", name: "buildExpired", widget: "boolean", required: false, default: false }
          - { label: "Build Future", name: "buildFuture", widget: "boolean", required: false, default: false }
          - { label: "Google Analytics", name: "googleAnalytics", widget: "string", required: false, default: "{{ if .Site.Params.verification.google }}{{ . }}{{ end }}" }
          - label: imaging
            name: imaging
            widget: object
            fields:
              - { label: "Anchor", name: "anchor", widget: "string" }
          - label: sitemap
            name: sitemap
            widget: object
            fields:
              - { label: "changefreq", name: "changefreq", widget: "select", options: [ "always", "hourly", "daily", "weekly", "monthly", "yearly", "never", ], required: false }
              - { label: "filename", name: "filename", widget: "string", required: false }
              - { label: "priority", name: "priority", widget: "number", required: false, default: 0.5, value_type: "int", min: 0.0, max: 100 }
          - label: related
            name: related
            widget: object
            fields:
              - { label: "threshold", name: "threshold", widget: "number", required: false, default: 0, value_type: "int", min: 0, max: 10 }
              - { label: "toLower", name: "toLower", widget: "boolean", required: false, default: false }
{{ end }}